<?php
/**
 * WEB4PRO - Creating profitable online stores
 *
 * @author    vyurchenko@corp.web4pro.com.ua
 * @category  WEB4PRO
 * @package   Web4pro_Stockstatus
 * @copyright Copyright (c) 2017 WEB4PRO (http://www.web4pro.net)
 * @license   http://www.web4pro.net/license.txt
 */
?>
<?php $stockStatusHelper = $this->helper('Web4pro\Stockstatus\Helper\Data'); ?>
<?php $_product = $block->getProduct(); ?>
<?php if ($block->displayProductStockStatus()): ?>
    <?php echo $stockStatusHelper->getNewStockStatus($_product); ?>
<?php endif; ?>
<?php if($_product->getTypeId() == 'configurable'): ?>
<script type="text/x-magento-init">
{
    "*": {
        "Web4pro_Stockstatus/js/stockstatus": {
           "productsOptions": <?php echo $stockStatusHelper->isConfigurableProduct($_product); ?>
        }
    }
}
</script>
<?php endif; ?>